---
title: "Constraint_Based_WS"
output: html_notebook
---

Ultilizing the IAMB feature in bnlearn package to learn the structure of a Bayesian Network.
Install packages
```{r}
# install.packages(`bnlearn`)
# install.packages("BiocManager")
# BiocManager::install("Rgraphviz")
```

Setup
```{r}
# Load packages
library(bnlearn)
library(Rgraphviz)

# Set data path
DATA_PATH <- paste0(getwd(), "/data/")
```


Data
```{r}
# Define file paths
l30_hist <- paste0(DATA_PATH, "turner/LSDS-30_histomorphometry_turnerTRANSFORMED.csv")
l40_bone <- paste0(DATA_PATH, "ko/LSDS-40_Bone_Biomechanical_LDSD-40_biomechanical_KoTRANSFORMED.csv")
l40_hist <- paste0(DATA_PATH, "ko/LSDS-40_histomorphometry_LSDS-40_histomorphometry_KoTRANSFORMED.csv")
l41_tomo <- paste0(DATA_PATH, "ko/LSDS-41_peripheral_quantitative_computed_tomography_pQCT_LSDS-41_pQCT_KoTRANSFORMED.csv")
```


Cooked Functions
```{r}
# Func: shortenColumnNames
# Desc: Shortens the column names by keeping the first four characters of each name.
#
# Param:
#   column_names: Character vector of column names to be shortened.
#   pattern: Optional. Pattern to split the column names. Default is "_".
#
# Returns:
#   Character vector with shortened column names.
shortenColumnNames <- function(column_names, pattern = "_") {
    shortened_names <- sapply(strsplit(column_names, pattern), function(x) paste0(substr(x, 1, 4), collapse = pattern))
    return(shortened_names)
}



# Func: convertColumnsToNumeric
# Desc: Converts columns containing a specified keyword in their names to numeric values.
#
# Param:
#   data: Data frame to be modified.
#   keyword: Keyword to match in the column names.
#
# Returns:
#   Modified data frame with the specified columns converted to numeric values.
convertColumnsToNumeric <- function(data, keyword) {
    for (i in 1:ncol(data)) {
        if (grepl(keyword, colnames(data)[i])) {
            data[, i] <- as.numeric(data[, i])
        }   
    }
    return(data)
}



# Func: readCSVFile
# Desc: Reads a CSV file and returns the data frame.
#
# Param:
#   file_path: Character string specifying the path of the CSV file.
#   header: Optional logical value indicating whether the file has a header row. Default is TRUE.
#   skip_rows: Optional numeric value specifying the number of rows to skip. Default is 0.
#
# Returns:
#   Data frame containing the contents of the CSV file.
readCSVFile <- function(file_path, header = TRUE, skip_rows = 0) {
    picked_data_path <- paste0(DATA_PATH, file_path)
    data <- read.csv(picked_data_path, header = header, skip = skip_rows)
    return(data)
}

```


Turner/LSDS-15_microCT
```{r}
data <- readCSVFile("alwood/LSDS-15_microCT_alwoodTRANSFORMED.csv")
dsub_set <- data[, -c(1:3)]
```


Turner/LSDS-9_microCT
```{r}
data <- readCSVFile("turner/LSDS-9_microCT_turnerTRANSFORMED.csv")

# Convert necessary columns to numeric
data$cortical_thickness_micrometer <- as.numeric(data$cortical_thickness_micrometer)
data <- convertColumnsToNumeric(data, "cancellous")

# Shorten column names
colnames(data) <- shortenColumnNames(colnames(data))

dsub_set <- data[, -c(1:3)]
```


Ko/LSDS-40_microCT
```{r}
data <- readCSVFile("ko/LSDS-40_microCT_LSDS-40_microCT_KoTRANSFORMED.csv", skip_rows = 1)

# Convert necessary columns to numeric
data$Fem.Length..mm. <- as.numeric(data$Fem.Length..mm.)

# Clean up column names
for (i in 1:ncol(data)) {
    if (grepl("_", colnames(data)[i])) {
        colnames(data)[i] <- shortenColumnNames(colnames(data)[i])
    }
}

# Remove first 5 columns
dsub_set <- data[, -c(1:5)]
```


Constraint-based learning algorithms
```{r}
# Learn the DAG structure
iamb_dag <- bnlearn::iamb.fdr(dsub_set)
graph_dag <- bnlearn::as.graphNEL(iamb_dag)


# Graphviz plot attributes
graph_attrs <- list(
    rankdir = "LR",     # Left to right orientation
    size = "10,10",     # Size of graph
    bgcolor = "white"
    )
node_attrs <- list(
    fontsize = 64, 
    fontcolor = "black", 
    shape = "circle", 
    style = "filled", 
    fillcolor = "lightyellow"
    )
edge_attrs <- list(
    fontsize = 128,
    color = "darkgray"
    )

# Plot the DAG
plot(graph_dag, attrs = list(graph = graph_attrs, node = node_attrs, edge = edge_attrs))
```