---
title: "Constraint_Based_WS"
output: html_notebook
---

Ultilizing the IAMB feature in bnlearn package to learn the structure of a Bayesian Network.
Install packages
```{r}
# install.packages(`bnlearn`)
# install.packages("BiocManager")
# BiocManager::install("Rgraphviz")
```

Setup
```{r}
# Load packages
library(bnlearn)
library(Rgraphviz)

# Set data path
DATA_PATH <- paste0(getwd(), "/data/")
```


Data
```{r}
# Define file paths
l30_hist <- paste0(DATA_PATH, "turner/LSDS-30_histomorphometry_turnerTRANSFORMED.csv")
l40_bone <- paste0(DATA_PATH, "ko/LSDS-40_Bone_Biomechanical_LDSD-40_biomechanical_KoTRANSFORMED.csv")
l40_hist <- paste0(DATA_PATH, "ko/LSDS-40_histomorphometry_LSDS-40_histomorphometry_KoTRANSFORMED.csv")
l41_tomo <- paste0(DATA_PATH, "ko/LSDS-41_peripheral_quantitative_computed_tomography_pQCT_LSDS-41_pQCT_KoTRANSFORMED.csv")
```


Turner/LSDS-15_microCT
```{r}
# Pick data
picked_data <- paste0(DATA_PATH, "alwood/LSDS-15_microCT_alwoodTRANSFORMED.csv")
data <- read.csv(picked_data, header=TRUE)
dsub_set <- data[, -c(1:3)]
```


Turner/LSDS-9_microCT
```{r}
# Pick data
picked_data <- paste0(DATA_PATH, "turner/LSDS-9_microCT_turnerTRANSFORMED.csv")
data <- read.csv(picked_data, header=TRUE)

# Convert necessary columns to numeric
data$cortical_thickness_micrometer <- as.numeric(data$cortical_thickness_micrometer)
for (i in 1:ncol(data)) {
    # Loop through all columns with "cancellous" in the name and convert to numeric
    if (grepl("cancellous", colnames(data)[i])) {
        data[, i] <- as.numeric(data[, i])
    }   
}

# Shorten column names
colnames(data) <- sapply(strsplit(colnames(data), "_"), function(x) paste0(substr(x, 1, 4), collapse = "_"))

dsub_set <- data[, -c(1:3)]
```


Ko/LSDS-40_microCT
```{r}
# Pick data
picked_data <- paste0(DATA_PATH, "ko/LSDS-40_microCT_LSDS-40_microCT_KoTRANSFORMED.csv")
data <- read.csv(picked_data, header=TRUE, skip=1) # Skip first row

# Clean up column names
for (i in 1:ncol(data)) {
    if (grepl("_", colnames(data)[i])) {
        colnames(data)[i] <- sapply(strsplit(colnames(data)[i], "_"), function(x) paste0(substr(x, 1, 4), collapse = "_"))
    }
}

# Convert necessary columns to numeric
data$Fem.Length..mm. <- as.numeric(data$Fem.Length..mm.)

# Remove first 5 columns
dsub_set <- data[, -c(1:5)]
```

Constraint-based learning algorithms
```{r}
# Learn the DAG structure
iamb_dag <- bnlearn::iamb.fdr(dsub_set)
graph_dag <- bnlearn::as.graphNEL(iamb_dag)


# Graphviz plot attributes
graph_attrs <- list(
    rankdir = "LR",     # Left to right orientation
    size = "10,10",     # Size of graph
    bgcolor = "white"
    )
node_attrs <- list(
    fontsize = 64, 
    fontcolor = "black", 
    shape = "circle", 
    style = "filled", 
    fillcolor = "lightyellow"
    )
edge_attrs <- list(
    fontsize = 128,
    color = "darkgray"
    )

# Plot the DAG
plot(graph_dag, attrs = list(graph = graph_attrs, node = node_attrs, edge = edge_attrs))
```








IAMB
```{r}
iamb_dag <- bnlearn::iamb(dsub_set)
graph_dag <- bnlearn::as.graphNEL(iamb_dag)
plot(graph_dag)
```

Fast-IAMB
```{r}
fast_iamb_dag <- bnlearn::fast.iamb(dsub_set)
graph_dag <- bnlearn::as.graphNEL(fast_iamb_dag)
plot(graph_dag)
```

Inter-IAMB
```{r}
inter_iamb_dag <- bnlearn::inter.iamb(dsub_set)
graph_dag <- bnlearn::as.graphNEL(inter_iamb_dag)
plot(graph_dag)
```

IAMB-FDR
```{r}
iamb_fdr_dag <- bnlearn::iamb.fdr(dsub_set)
graph_dag <- bnlearn::as.graphNEL(iamb_fdr_dag)
plot(graph_dag)
```