---
title: "OSDR IAMB"
output: html_notebook
---


Install packages
```{r}
# install.packages(`bnlearn`)
# install.packages("BiocManager")
# BiocManager::install("Rgraphviz")
# install.packages(c("psych","lavaan"), dependencies=TRUE)
# install.packages("Rmpfr")
```


Setup
```{r}
# Load packages
library(bnlearn)
library(Rgraphviz)
library(psych)
library(Rmpfr)

# Set data path
DATA_PATH <- paste0(getwd(), "/data/")
LIB_PATH <- paste0(getwd(), "/src/lib/")
PLOT <- paste0(LIB_PATH, "plot_IAMB.R")
```


Dumb old code yuck
```{r}
main <- paste0(LIB_PATH, "turner_GLDS351_Metaphysis.R")
main <- paste0(LIB_PATH, "turner_GLDS351_Epiphysis.R")
main <- paste0(LIB_PATH, "turner_GLDS351.R")
main <- paste0(LIB_PATH, "turner_LSDS_30.R")
main <- paste0(LIB_PATH, "ko.R")
main <- paste0(LIB_PATH, "alwood_LSDS_15.R")
```


Lauren Dataset
```{r}
main <- paste0(LIB_PATH, "GWAS_lauren.R")
```


```{r}
path_bgd <- paste0(DATA_PATH, "GLDS-366/bgd.csv")
set_bgd <- read.csv(path_bgd, header=T)
path_fpg <- paste0(DATA_PATH, "GLDS-366/foci_per_gy.csv")
set_fpg <- read.csv(path_fpg, header=T)

pdag_bgd <- iamb(x=set_bgd,alpha = 0.05)
dag_bgd <- cextend(pdag_bgd)
pdag_fpg <- iamb(x=set_fpg,alpha = 0.05)
dag_fpg <- cextend(pdag_fpg)

fitted = bn.fit(dag_bgd, set_bgd, method = "mle-g")

bn.fit.xyplot(fitted)
```


```{r}
bayes.factors = bf.strength(dag_bgd, data = set_bgd)
strength.plot(dag_bgd, strength = bayes.factors, main = "bayes.factors", shape = "rectangle",
    highlight = list(nodes = "xray", arcs = incident.arcs(dag_bgd, "xray"),
    col = "darkblue", fill = "lightblue"))
```


ðŸ˜²ðŸ­ Deploy Constraint-based learning algorithms ðŸ­ðŸ˜²
```{r}
source(main)
source(PLOT)
```