---
title: "READ_OSDR"
output: html_notebook
---


Install packages
```{r}
# install.packages(`bnlearn`)
# install.packages("BiocManager")
# BiocManager::install("Rgraphviz")
# install.packages(c("psych","lavaan"), dependencies=TRUE)
```


Setup
```{r}
# Load packages
library(bnlearn)
library(Rgraphviz)
library(psych)
library(lavaan)

# Set data path
DATA_PATH <- paste0(getwd(), "/data/")
```


Turner GLDS-351
```{r}
g351 <- paste0(DATA_PATH, "turner/GLDS-351.csv")
glds <- read.csv(g351, header=T, stringsAsFactors=F)
glds$expose <- ifelse(glds$Teatment=="Ground Control",0,1)
glds<- glds[7:30,c(5:7,11,13,16:19,22:25)]  

# Make component variables
mass      <- pca(r=glds[,c("DXA_BMC_mg","DXA_BMD_mg_per_mmsq")],nfactors=1,scores = T)
trab_meta <- pca(r=glds[,c("metaphysis_canc_Tb_Sp_micrometer","metaphysis_canc_Tb_N_1per_mm")],nfactors=1,scores = T)
trab_epiph <- pca(r=glds[,c("epiphysis_canc_Tb_Sp_micrometer","epiphysis_canc_Tb_N_1per_mm")],nfactors=1,scores = T)

glds$mass <- as.vector(mass$scores)
glds$trab_meta <- as.vector(trab_meta$scores)
glds$trab_epiph <- as.vector(trab_epiph$scores)

# Standardize site-specific/single variable mass measures
names(glds)[5] <- "mass_meta"
glds$mass_meta <- scale(glds$mass_meta)

names(glds)[9] <- "mass_epiph"
glds$mass_epiph <- scale(glds$mass_epiph)

# Final dataset
glds <- glds[,c("expose","mass","mass_meta","mass_epiph","trab_meta","trab_epiph")]

rm(list=c("mass","trab_epiph","trab_meta"))

dsub_set <- glds
title <- "Turner GLDS-351"
```


Turner LSDS-30
```{r}
l30 <- paste0(DATA_PATH, "turner/LSDS-30_histomorphometry_turnerTRANSFORMED.csv")
turner <- read.csv(l30, header=T, stringsAsFactors=F)
turner <- turner[,c(1,3:9)] 
turner$expose <- ifelse(turner$Spaceflight=="Space Flight",1,0)
names(turner)[3:8] <- c("mass","labellength","cont_bf","ceased_bf","MAR","osteoc_per") 
  
# Create measures
resorp <- pca(r=turner[,c("labellength","osteoc_per")],nfactors=1,scores=T)
form   <- pca(r=turner[,c("ceased_bf","MAR")],nfactors=1,scores=T)
  
turner$resorp <- as.vector(resorp$scores)
turner$form   <- as.vector(form$scores)*-1  ## form loads "backwards"; multiply by -1 to fix
turner$mass   <- scale(turner$mass)
  
turner <- turner[,c(9,3,10:11)]
rm(list=c("form","resorp"))

dsub_set <- turner
title <- "Turner LSDS-30"
```


All Ko
```{r}
pko1 <- paste0(DATA_PATH, "ko/LSDS-40_Bone_Biomechanical_LDSD-40_biomechanical_KoTRANSFORMED.csv")
pko2 <- paste0(DATA_PATH, "ko/LSDS-40_histomorphometry_LSDS-40_histomorphometry_KoTRANSFORMED.csv")
pko3 <- paste0(DATA_PATH, "ko/LSDS-40_microCT_LSDS-40_microCT_KoTRANSFORMED.csv")
pko4 <- paste0(DATA_PATH, "ko/LSDS-41_peripheral_quantitative_computed_tomography_pQCT_LSDS-41_pQCT_KoTRANSFORMED.csv")

nastring <- c("           *","epiphysis broken")    # things we want R to read as NA
ko1 <- read.csv(pko1, header=T, stringsAsFactors=F)
ko2 <- read.csv(pko2, header=T, stringsAsFactors=F, na.strings=nastring)
ko3 <- read.csv(pko3, header=T, stringsAsFactors=F, na.strings=nastring)
ko4 <- read.csv(pko4, header=T, stringsAsFactors=F)

# Subest to needed columns/rows
ko1 <- ko1[,c(1,3:4,8:10)]
ko2 <- ko2[!(is.na(ko2$Source.Name)),c(1,7:11)]
ko3 <- ko3[,c(1,10,13:17)]
ko4 <- ko4[,c(1,4:7)]


# Rename columns
names(ko1) <- c("ID","PWB","duration","stiffness","load.max","load.fail")
names(ko2) <- c("ID","OBSBS","OCSBS",'MSBS',"MAR","BFRBS")
names(ko3) <- c("ID","BVTV","trab.num","trab.thick","trab.sep","BMD","cort.thick")
names(ko4) <- c("ID","BMD0","BMD1","BMD2","BMD4")

# create indicators of source file
ko1$k1 <- 1
ko2$k2 <- 1
ko3$k3 <- 1
ko4$k4 <- 1

# Merge files
ko12 <- merge(ko1,ko2,by="ID",all.x=T,all.y=T)
ko123 <- merge(ko12,ko3,by="ID",all=T)
ko1234 <- merge(ko123,ko4,by="ID",all=T) 

# Fill in missing indicators with 0
ko1234$k1[is.na(ko12$k1)] <-0
ko1234$k2[is.na(ko12$k2)] <-0
ko1234$k3[is.na(ko12$k3)] <-0
ko1234$k4[is.na(ko12$k4)] <-0

# Keep only needed rows
ko <- ko1234[!(is.na(ko1234$stiffness)),]
ko$unload <- 0*(ko$PWB=='PWB100')+30*(ko$PWB=="PWB70")+60*(ko$PWB=="PWB40")+80*(ko$PWB =="PWB20")
ko$dur <- 7*(ko$duration=='1wk')+14*(ko$duration=='2wk')+28*(ko$duration=='4wk')
ko <- ko[,c('BVTV','BMD','trab.sep','trab.num','MSBS','OCSBS','BFRBS','load.max','load.fail','unload','dur')]

# Transform to numeric
ko$BVTV <- as.numeric(as.character(ko$BVTV))
ko$BMD <- as.numeric(as.character(ko$BMD))
ko$trab.sep <- as.numeric(as.character(ko$trab.sep))
ko$trab.num <- as.numeric(as.character(ko$trab.num))

mass <- pca(r=ko[,c("BVTV","BMD")], nfactors = 1, scores = T)
trab <- pca(r=ko[,c("trab.sep","trab.num")], nfactors = 1, scores = T)
form   <- pca(r=ko[,c("MSBS","BFRBS")], nfactors = 1, scores = T)
stren <- pca(r=ko[,c("load.max","load.fail")], nfactors = 1, scores = T)

ko$mass <- as.vector(mass$scores[,1])
ko$trab <- as.vector(trab$scores[,1])
ko$stren <- as.vector(stren$scores[,1])
ko$expose <- ((ko$unload*ko$dur)-mean(ko$unload*ko$dur))/(sd(ko$unload*ko$dur))
ko$resorp <- scale(ko$OCSBS)
ko$form   <- as.vector(form$scores)


ko <- ko[,c("unload","dur","expose","mass","trab","stren","resorp","form")]

rm(list=c("mass","trab","form","stren"))

dsub_set <- ko
title <- "All Ko(4/4)"
```


Alwood LSDS-15
```{r}
a15 <- paste0(DATA_PATH, "alwood/LSDS-15_microCT_alwoodTRANSFORMED.csv")
alwood <- read.csv(a15, header=T, stringsAsFactors=F)
alwood <- alwood[11:37,c(3:6,9)]
alwood$expose <- ifelse(alwood$Factor.Value=="Flight",1,0)
names(alwood)[2:5] <- c("thick","sep","num","bvtv")

trab <- pca(r=alwood[,c("sep","num")],nfactors=1,scores = T)
mass <- pca(r=alwood[,c("thick","bvtv")],nfactors=1,scores=T)

alwood$trab <- as.vector(trab$scores)
alwood$mass <- as.vector(mass$scores)

alwood <- alwood[,c("expose","trab","mass")]

rm(list=c("trab","mass"))

dsub_set <- alwood
title <- "Alwood LSDS-15"
```


Constraint-based learning algorithms
```{r}
# Learn the DAG structure
iamb_dag <- bnlearn::iamb(dsub_set)
fast_iamb_dag <- bnlearn::fast.iamb(dsub_set)
inter_iamb_dag <- bnlearn::inter.iamb(dsub_set)
iamb_fdr_dag <- bnlearn::iamb.fdr(dsub_set)

iamb_graph <- bnlearn::as.graphNEL(iamb_dag)
fast_iamb_graph <- bnlearn::as.graphNEL(fast_iamb_dag)
inter_iamb_graph <- bnlearn::as.graphNEL(inter_iamb_dag)
iamb_fdr_graph <- bnlearn::as.graphNEL(iamb_fdr_dag)

# Graphviz plot attributes
graph_attrs <- list(
    rankdir = "LR",     # Left to right orientation
    size = "5,5",       # Size of graph
    bgcolor = "white"
    )
node_attrs <- list(
    # fontsize = 32, 
    fontcolor = "black", 
    shape = "circle", 
    style = "filled", 
    fillcolor = "lightyellow"
    )
edge_attrs <- list(
    # fontsize = 12,
    color = "black"
    )

# Plot the DAG
# par(mfrow = c(1,4))

plot_title <- paste0("ðŸ˜²ðŸ­ IAMB âž¤ ", title, " ðŸ­ðŸ˜²")
plot(iamb_graph, attrs = list(graph = graph_attrs, node = node_attrs, edge = edge_attrs))
title(plot_title, line = -5.5, cex.main = 3)
```